# basic options
title: Test Blog
author: Musikobios
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  igardenaua

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
